version: '3'
services:
  postgresql:
    image: postgres:13
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

volumes:
  database:
    driver: local
